eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true




management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      productBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      productService:
        maxAttempts: 3
        waitDuration: 5s

  ratelimiter:
    instances:
      productRateLimiter:
        limitRefreshPeriod: 4s
        limitForPeriod: 2
        timeoutDuration: 0s


      productRateLimiterForId:
        limitRefreshPeriod: 4s
        limitForPeriod: 2
        timeoutDuration: 0s

      categoryRateLimiter:
        limitRefreshPeriod: 4s
        limitForPeriod: 4
        timeoutDuration: 0s

      categoryRateLimiterForId:
        limitRefreshPeriod: 4s
        limitForPeriod: 2
        timeoutDuration: 0s

      userRateLimiter:
        limitRefreshPeriod: 4s
        limitForPeriod: 2
        timeoutDuration: 0s

      userRateLimiterForId:
        limitRefreshPeriod: 4s
        limitForPeriod: 2
        timeoutDuration: 0s



